### ISSUE TITLE
netToGrossCalculation count() verb returns "Argument 'x' is not a vector: list"

### ISSUE THREAD

**Issue by backslashpaige** [drofphilosophe/USElecData#10]
https://github.com/drofphilosophe/USElecData/blob/378603e8276d725b95eaf193af9afbc83fb88496/src/EPA-CEMS/netToGrossCalculation.R#L234

I get the error: "Argument 'x' is not a vector: list"

which is weird because I do see orispl.code as a column in the table called crosswalk.cems...

**Comment by drofphilosophe** [comment]
Can you show the output of `glimpse(crosswalk)`? I can't replicate the error and I wonder if there is a difference in data types with the crosswalk. 

Can you also post the packages you have loaded at that point with `(.packages())`. I'm worried there might be a name conflict with `count()`. When I run this file from a new session I have the following packages loaded:
` [1] "yaml"      "here"      "haven"     "lubridate" "forcats"   "stringr"   "dplyr"     "purrr"     "readr"     "tidyr"     "tibble"    "ggplot2"   "tidyverse" "stats"     "graphics"  "grDevices" "utils"     "datasets"` 
`[19] "methods"   "base"`

**Comment by drofphilosophe** [comment]
It turns out the behavior of `count()` has changed since I wrote this script. I've created a branch **issue-10** which should resolve this error using `group_by()` and `summarize()` instead of `count()`.
