### ISSUE TITLE
incompatible vector issue

### ISSUE THREAD

**Issue by backslashpaige** [drofphilosophe/USElecData#15]
https://github.com/drofphilosophe/USElecData/blob/ef18a2f4986708677f49509d8e42a1b7968a0eea/src/EPA-CEMS/netToGrossCalculation.R#L310

im getting this error here: 

Error in stop_vctrs(x_size = x_size, y_size = size, x_arg = x_arg, class = c("vctrs_error_incompatible_size",  (netToGrossCalculation.R#302): Can't recycle input of size 287 to size 0.
Show stack trace

when I run just the rename i get a tibble: 0x6. wondering if it was supposed to be empty?

**Comment by drofphilosophe** [comment]
A zero-length data frame was loaded resulting from a bug that failed to create monthly data. This has been resolved.
