### ISSUE TITLE
CEMS Facility issue

### ISSUE THREAD

**Issue by backslashpaige** [drofphilosophe/USElecData#34]
When I do the full build I get an error about missing crosswalk files. Which seems to be coming from an error in the CEMS Facility build. When I do just the CEMS facility build I get this error. any thoughts? Maybe a missing package? I am in the USElecData conda environment.

[Untitled.pdf](https://github.com/drofphilosophe/USElecData/files/11004364/Untitled.pdf)

**Comment by drofphilosophe** [comment]
Seems like there is an inconsistency between one of our source data files. I've added code to check to see if the final facility tibble is an `sf` object, if so it drops the geometry. It will then try to drop a column named `geometry` which will handle tibbles that have geometry information but are not classed as `sf` objects.
