### ISSUE TITLE
error due to incompatible year and quarter variables

### ISSUE THREAD

**Issue by backslashpaige** [drofphilosophe/USElecData#8]
https://github.com/drofphilosophe/USElecData/blob/b6ab3e1324f0a5441d895d3cc3d0559e7e49e0d1/src/EPA-CEMS/loadCEMSData.R#L102

Looks like the input vars for Year and Quarter are in character and the output file Year and Quarter vars are in integer

I ran this and it fixed the year and quarters var but still an issue with the datetime

input.file.log$Year <- as.integer(input.file.log$Year)
input.file.log$Quarter <- as.integer(input.file.log$Quarter)

**Comment by backslashpaige** [comment]
So now when I try to run it, I now get an error that the datetime variable is not the right format. investigating further, I am pretty sure the issue is upstream - that my SourceFileLog.csv had 4 variable headers but is all empty. which makes sense since I haven't downloaded anything yet. So I *think the needed fix is to establish data types for those variables in the event that the .csv is all missing. Does that follow?

**Comment by drofphilosophe** [comment]
I pushed new changes that explicitly define data types when loading `SourceFileLog.csv` and deal with the case when the code that constructs the `output.file.log` doesn't find any files.

**Comment by backslashpaige** [comment]
Thanks for this update. I am still having trouble with this file. Right now the problem is the input.file.log is an empty Table 0x7. trying to diagnose on my end and welcome any thoughts you have on the issue. right now i see that the files are all downloaded in USElecData/data/source/EPA-CEMS/hourly/XX where XX = year. So I don't think the issue is that the source files are missing.

**Comment by drofphilosophe** [comment]
It might be that you have a corrupted `SourceFileLog.csv` -- in that it contains a condition I never anticipated (zero processed files). Can you delete `USElecData/data/source/EPA-CEMS/hourly/SourceFileLog.csv` and then run the Python script `src/EPA-CEMS/retconSourceFileDB.py` and see if that solves the problem? That script is an undocumented way to rebuild `SourceFileLog.csv`. If that works, I'll probably need to document it...

**Comment by backslashpaige** [comment]
alright good news is - that change definitely fixed the issue with missing input file. now I can get through to line 281. bad news is I now have trouble executing the big for loop that starts on line 281. 

first I have an issue getting the progress bar to download, as library(tcltk) does not work and directs me to xquartz.com site which is no longer maintained. but this is fine because i think you mentioned this will be resolved when you move to having everything be executed in anaconda. so, i commented out all the progress bar commands in the code block.

after this, I am getting an error where is doesn't like the 'else' at the very end of the code block here: 
------------------
else {
      warning(paste("No source data for year", yr,"quarter",q))
    }

Error in (function (file = "", n = NULL, text = NULL, prompt = "?", keep.source = getOption("keep.source"), : <text>:517:7: unexpected 'else'
-------------------------

Since this is just to write something I commented this out too and re-ran. and then I get an error that im not sure how to address.

Error in (function (file = "", n = NULL, text = NULL, prompt = "?", keep.source = getOption("keep.source"), : <text>:522:0: unexpected end of input
520:   }

any thoughts on other diagnostics to test to get this code block to run?

**Comment by backslashpaige** [comment]
^^ not sure whey some of the test is super large above... mysteries of git...

**Comment by drofphilosophe** [comment]
Do you still get the error message about the **unexpected else** or **error in (function...**? It seems like those might be from braces not lining up.
