### ISSUE TITLE
new error: 'year' not found

### ISSUE THREAD

**Issue by backslashpaige** [drofphilosophe/USElecData#9]
https://github.com/drofphilosophe/USElecData/blob/6e5bed9ba5b337cd9fb5ac46be8df4f7b64a1a40/src/EPA-CEMS/loadCEMSData.R#L121

good news branch is working! bad news (not actually bad) when i run this code block i get "Error in group_by(Year, Quarter) (loadCEMSData.R#121): object 'Year' not found"

which is strange because i can see that the Year is an integer variable in input.file.log. so i guessed that it wasn't piping properly, and added a %>% at the end of line 120 and that seemed to fix it.

**Comment by drofphilosophe** [comment]
I've removed a line of diagnostic code that was causing the error. I'll go ahead and merge this into main.
